### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by McGuitton** [draanPSP/msipl_installer#1]
hi DraanPSP,
thank you for your work.
I try to run your script on windows 11 with cygwin64, I install module wmi and win32 for that.
I have a problem during the run.
I am not sure that my the physical drive number is the good one because I have a permission denied but I am an administrator.
Can you tell me the procedure to get the physical drive number and how to fix my permission denied if you know?

_$ python3 msipl.py --pdisk 2 --info
Traceback (most recent call last):
  File "C:\cygwin64\home\Laury\msipl.py", line 101, in <module>
    with openDisk() as f:
  File "C:\cygwin64\home\Laury\msipl.py", line 74, in openDisk
    return open(diskID, 'rb+')
PermissionError: [Errno 13] Permission denied: '\\\\.\\PHYSICALDRIVE2'_

**Comment by McGuitton** [comment]
i close this issue sorry i'am a really noob. Click right on cygwin64 and execute like an administrator
